import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import SessionProvider from "./components/SessionProvider";
import AppProvider, { CartItemsProvider } from "./components/AppContext";
import ClientTabsWrapper from "./components/layout/ClientTabsWrapper";
import ShowTabsOnAdminPages from "./components/layout/ShowTabsOnAdminPages";
import Footer from "./components/layout/Footer";

const roboto = Roboto({ 
  weight: ['400', '500', '700'],
  subsets: ["latin"], 
  variable: "--font-roboto" 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <SessionProvider session={session}>
          <AppProvider>
            <CartItemsProvider>
              <main className="max-w-4xl mx-auto p-4">
                <Header />
                <ShowTabsOnAdminPages />
                {children}
                <Footer />
              </main>
            </CartItemsProvider>
          </AppProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
 